### ISSUE TITLE
run:detached may need a timeout to read all stdout output

### ISSUE THREAD

**Issue by dblock** [dblock/heroku-commander#2]
It looks like Heroku reports a process completed status before flushing all output to heroku logs::tail.

```
** Execute cron:production:heat_import
Running: heroku run:detached "(rake db:heat_indexes:rebuild 2>&1 ; echo rc=\$?)" --app gravity-production
Started: 4852
4852: Running `(rake db:heat_indexes:rebuild 2>&1 ; echo rc=$?)` detached... up, run.9156
Heroku detached pid run.9156 up.
Running: heroku logs -p run.9156 --tail --app gravity-production
rake aborted!

Problem:
 The command `rake db:heat_indexes:rebuild` failed with exit status .
Summary:
 The command rake db:heat_indexes:rebuild failed with exit status .
    Creating scope :sitemappable. Overwriting existing method Film.sitemappable.
    Creating scope :sitemappable. Overwriting existing method Post.sitemappable.
    Checking for updates to ArtistSimilarityIndex
    ... skipping 2 line(s) ...
    Checking for updates to TagPartitionedArtworkSimilarityIndex
    Checking for updates to HistoricalSalesIndex
Resolution:
 Examine the command line and refer to the command documentation.
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/bundler/gems/heroku-commander-6ba57410b357/lib/heroku/runner.rb:70:in `check_exit_status!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/bundler/gems/heroku-commander-6ba57410b357/lib/heroku/runner.rb:53:in `run_detached!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/bundler/gems/heroku-commander-6ba57410b357/lib/heroku/runner.rb:20:in `run!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/bundler/gems/heroku-commander-6ba57410b357/lib/heroku/commander.rb:21:in `run'
/mnt/jenkins/workspace/gravity-heat-import-cron/lib/tasks/heroku.rake:18:in `execute'
/mnt/jenkins/workspace/gravity-heat-import-cron/lib/tasks/cron.rake:27:in `block (3 levels) in <top (required)>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/bin/rake:23:in `load'
/home/jenkins/.rvm/gems/ruby-1.9.3-p286/bin/rake:23:in `<main>'
Tasks: TOP => cron:production:heat_import
Started: 4913
4913: 2013-02-01T20:05:26+00:00 heroku[run.9156]: State changed from starting to up
4913: 2013-02-01T20:05:25+00:00 heroku[run.9156]: Starting process with command `(rake db:heat_indexes:rebuild 2>&1 ; echo rc=$?)`
4913: 2013-02-01T20:05:56+00:00 app[run.9156]: Creating scope :sitemappable. Overwriting existing method Film.sitemappable.
4913: 2013-02-01T20:05:59+00:00 app[run.9156]: Creating scope :sitemappable. Overwriting existing method Post.sitemappable.
4913: 2013-02-01T20:06:15+00:00 app[run.9156]: Checking for updates to ArtistSimilarityIndex
4913: 2013-02-01T20:06:26+00:00 app[run.9156]: Checking for updates to RelatedGenesIndex
4913: 2013-02-01T20:06:36+00:00 app[run.9156]: Checking for updates to TagPartitionedArtworkSimilarityIndex
4913: 2013-02-01T20:06:40+00:00 app[run.9156]: Checking for updates to HistoricalSalesIndex
4913: 2013-02-01T20:06:59+00:00 heroku[run.9156]: State changed from up to complete
Terminating 4913.
4852: Use `heroku logs -p run.9156` to view the output.
Errno::EIO: Input/output error - /dev/pts/0
Waiting: 4852
Build step 'Execute shell' marked build as failure
```

The full command output was:

```
Feb 01 15:05:26 gravity-production heroku/run.9156:  State changed from starting to up
Feb 01 15:05:41 gravity-production heroku/run.9156:  Starting process with command `(rake db:heat_indexes:rebuild 2>&1 ; echo rc=$?)`
Feb 01 15:06:08 gravity-production app/run.9156:  Creating scope :sitemappable. Overwriting existing method Film.sitemappable.
Feb 01 15:06:11 gravity-production app/run.9156:  Creating scope :sitemappable. Overwriting existing method Post.sitemappable.
Feb 01 15:06:27 gravity-production app/run.9156:  Checking for updates to ArtistSimilarityIndex
Feb 01 15:06:38 gravity-production app/run.9156:  Checking for updates to RelatedGenesIndex
Feb 01 15:06:47 gravity-production app/run.9156:  Checking for updates to TagPartitionedArtworkSimilarityIndex
Feb 01 15:06:52 gravity-production app/run.9156:  Checking for updates to HistoricalSalesIndex
Feb 01 15:06:59 gravity-production heroku/run.9156:  State changed from up to complete
Feb 01 15:07:05 gravity-production app/run.9156:  Checking for updates to FilteredEventSearchIndex
Feb 01 15:07:09 gravity-production app/run.9156:  rc=0
```

So in this case we should not have stopped reading input at "State changed from up to complete".

**Comment by dblock** [comment]
Fixed via https://github.com/dblock/heroku-commander/commit/b7268dfafca8103eaa2c268103a58935b0386d7d.
